CREATE TABLE TIPUS_DE_PLAZA(
    NOM VARCHAR2 (50) PRIMARY KEY,
    FUNCIO VARCHAR2(50)
);
CREATE TABLE PLAZA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM VARCHAR2(50),
    SALARI FLOAT,
    CODI_PLAZA_SUPERVISORA NUMBER,
    INFORME_SUPERVISIO VARCHAR2(50),
    NOM_TIPUS_DE_PLAZA VARCHAR2(50),
    FOREIGN KEY (CODI_PLAZA_SUPERVISORA) REFERENCES PLAZA(CODI),
    FOREIGN KEY (NOM_TIPUS_DE_PLAZA) REFERENCES TIPUS_DE_PLAZA(NOM)
);

CREATE TABLE EMPLEAT(
    NUSS NUMBER PRIMARY KEY,
    NOM VARCHAR2 (50),
    LLINATGES VARCHAR2(50),
    EMAIL VARCHAR(50),
    IBAN VARCHAR(50)
);