DROP TABLE AUTOR;
CREATE TABLE AUTOR(
    ID NUMBER GENERATED AS IDENTITY,
    NOM VARCHAR2(50) ,
    COGNOMS VARCHAR (50),
    DATA_NAIXAMENT DATE,
    NACIONALITAT VARCHAR2(50),
    PRIMARY KEY (ID),
    UNIQUE (NOM, COGNOMS, NACIONALITAT)
);
CREATE TABLE EDITORIAL(
    ID NUMBER GENERATED AS IDENTITY,
    NOM VARCHAR2 (50),
    PRIMARY KEY (ID)
);
CREATE TABLE LLIBRE(
    ID NUMBER GENERATED AS IDENTITY,
    TITOL VARCHAR2 (50),
    ANYO NUMBER,
    EXEMPLARS NUMBER,
    ID_EDITORIAL NUMBER NOT NULL,
    ID_SECUELA NUMBER,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL(ID),
    FOREIGN KEY (ID_SECUELA) REFERENCES LLIBRE(ID),
    UNIQUE(TITOL, ANYO),
    CHECK (ANYO<2023),
    CHECK (EXEMPLARS>0)
);
CREATE TABLE AUTOR_LLIBRE(
    ID_AUTOR NUMBER,
    ID_LLIBRE NUMBER,
    PRIMARY KEY (ID_AUTOR, ID_LLIBRE),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID),
    FOREIGN KEY (ID_LLIBRE) REFERENCES LLIBRE(ID)
);
CREATE TABLE GENERE(
    NOM VARCHAR2(50) PRIMARY KEY
    
);
CREATE TABLE LLIBRE_GENERE(
    ID_LLIBRE NUMBER,
    NOM_GENERE VARCHAR(50),
    PRIMARY KEY (ID_LLIBRE, NOM_GENERE),
    FOREIGN KEY (ID_LLIBRE) REFERENCES LLIBRE(ID),
    FOREIGN KEY (NOM_GENERE) REFERENCES GENERE(NOM)
);
