CREATE TABLE TIPUS_DE_PLAZA(
    NOM VARCHAR2 (50) PRIMARY KEY,
    FUNCIO VARCHAR2(50) NOT NULL
);
CREATE TABLE PLAZA(
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    SALARI FLOAT NOT NULL ,
    CODI_PLAZA_SUPERVISORA NUMBER,
    INFORME_SUPERVISIO VARCHAR2(50),
    NOM_TIPUS_DE_PLAZA VARCHAR2(50),
    FOREIGN KEY (CODI_PLAZA_SUPERVISORA) REFERENCES PLAZA(CODI),
    FOREIGN KEY (NOM_TIPUS_DE_PLAZA) REFERENCES TIPUS_DE_PLAZA(NOM)
);

CREATE TABLE EMPLEAT(
    NUSS NUMBER PRIMARY KEY,
    NOM VARCHAR2 (50) NOT NULL,
    LLINATGES VARCHAR2(50)NOT NULL,
    EMAIL VARCHAR(50),
    IBAN VARCHAR(50) UNIQUE NOT NULL,
    CHECK (SUBSTR(IBAN,1,2) = 'ES')
);
CREATE TABLE OCUPA(
    NSS_EMPLEAT NUMBER,
    CODI_PLAZA NUMBER,
    DATA_INICI DATE NOT NULL,
    DATA_FI DATE,
    PRIMARY KEY (NSS_EMPLEAT, CODI_PLAZA),
    FOREIGN KEY (NSS_EMPLEAT) REFERENCES EMPLEAT(NUSS),
    FOREIGN KEY (CODI_PLAZA) REFERENCES PLAZA(CODI)
);
CREATE TABLE NOMINA(
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    IBAN_PAGAMENT NUMBER NOT NULL,
    IMPORT NUMBER NOT NULL,
    NSS_EMPLEAT NUMBER,
    CODI_PLAZA NUMBER,
    FOREIGN KEY (NSS_EMPLEAT) REFERENCES EMPLEAT(NUSS),
    FOREIGN KEY (CODI_PLAZA) REFERENCES PLAZA(CODI)
);
