CREATE TABLE PROVEIDOR(
    ID_PROVEIDOR NUMBER GENERATED AS IDENTITY,
    PIEZA VARCHAR2(50),
    PRIMARY KEY (ID_PROVEIDOR)
);

CREATE TABLE FABRICA (
    ID_FABRICA NUMBER GENERATED AS IDENTITY,
    NOMBRE VARCHAR2(50),
    PRIMARY KEY (ID_FABRICA)
);

CREATE TABLE APORTACIO(
    ID_FABRICA NUMBER ,
    ID_PROVEIDOR NUMBER,
    PRIMARY KEY (ID_FABRICA,ID_PROVEIDOR),
    FOREIGN KEY (ID_FABRICA) REFERENCES FABRICA(ID_FABRICA),
    FOREIGN KEY (ID_PROVEIDOR) REFERENCES PROVEIDOR(ID_PROVEIDOR)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER GENERATED AS IDENTITY,
    TIPO VARCHAR2(50),
    PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE CREA (
    ID_CATEGORIA NUMBER,
    ID_FABRICA NUMBER ,
    PRIMARY KEY (ID_CATEGORIA, ID_FABRICA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (ID_FABRICA) REFERENCES FABRICA(ID_FABRICA)
);

CREATE TABLE MODELO (
    ID_MODELO NUMBER GENERATED AS IDENTITY,
    ID_MODELO_MEJORADO NUMBER,
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50),
    PANTALLA VARCHAR2(50),
    POTENCIA VARCHAR2(50),
    ALMACENAMIENTO VARCHAR2(50),
    PRECIO FLOAT,
    STOCK_DISPONIBLE NUMBER,
    PRIMARY KEY (ID_MODELO),
    FOREIGN KEY (ID_MODELO_MEJORADO) REFERENCES MODELO(ID_MODELO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE TIENDA (
    ID_TIENDA NUMBER GENERATED AS IDENTITY,
    NOMBRE VARCHAR2(50),
    CIUDAD VARCHAR2(50),
    PRIMARY KEY (ID_TIENDA)
);

CREATE TABLE VENTA(
    ID_TIENDA NUMBER,
    ID_MODELO NUMBER,
    PRIMARY KEY (ID_TIENDA,ID_MODELO),
    FOREIGN KEY (ID_TIENDA) REFERENCES TIENDA(ID_TIENDA),
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO)
);

CREATE TABLE REPARTIDOR(
    NUSS NUMBER ,
    NOM VARCHAR2(50),
    MATRICULA VARCHAR2(7),
    PRIMARY KEY (NUSS)
);

CREATE TABLE CLIENTE (
    DNI VARCHAR2(9) ,
    NOM VARCHAR2(50),
    DIRECCION VARCHAR2(50),
    TELEFONO NUMBER,
    PRIMARY KEY (DNI)
);

CREATE TABLE COMANDA(
    ID_COMANDA NUMBER GENERATED AS IDENTITY,
    DNI_CLIENTE VARCHAR2(50) NOT NULL,
    NUSS_REPARTIDOR NUMBER,
    PRECIO_TOTAL FLOAT,
    FECHA_ENTREGA DATE,
    FECHA_PEDIDO DATE,
    PRIMARY KEY (ID_COMANDA),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
    FOREIGN KEY (NUSS_REPARTIDOR) REFERENCES REPARTIDOR(NUSS)
);
CREATE TABLE PERTENECE(
    ID_MODELO NUMBER,
    ID_COMANDA NUMBER,
    CANTIDAD NUMBER,
    PRIMARY KEY (ID_MODELO, ID_COMANDA),
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO),
    FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA(ID_COMANDA)
);